In [5]:
import pandas as pd
import numpy as np

In [69]:
df=pd.read_csv("/Users/prateek/Desktop/XLRI/Talentedge___Data_Science__files_for_today's_class__29th_June/cluster.csv")

In [8]:
df.head()


Id        age  gender       income  kids ownHome subscribe
0   1  47.316133    Male  49482.81044     2   ownNo     subNo
1   2  31.386839    Male  35546.28830     1  ownYes     subNo
2   3  43.200342    Male  44169.18638     0  ownYes     subNo
3   4  37.316995  Female  81041.98639     1   ownNo     subNo
4   5  40.954390  Female  79353.01444     3  ownYes     subNo

In [9]:
df_num=df

In [10]:
df_num.head()

Id        age  gender       income  kids ownHome subscribe
0   1  47.316133    Male  49482.81044     2   ownNo     subNo
1   2  31.386839    Male  35546.28830     1  ownYes     subNo
2   3  43.200342    Male  44169.18638     0  ownYes     subNo
3   4  37.316995  Female  81041.98639     1   ownNo     subNo
4   5  40.954390  Female  79353.01444     3  ownYes     subNo

In [16]:
df_num['female']=df_num['gender'].apply(lambda x: '1' if x=='Female' else '0')
df_num['ownHome']=df_num['ownHome'].apply(lambda x: '1' if x=='ownYes' else '0')
df_num['subscribe']=df_num['subscribe'].apply(lambda x: '0' if x=='subNo' else '1')

In [38]:
df_num.head()


age       income  kids ownHome subscribe female  sum1
0  47.316133  49482.81044     2       0         0      0     3
1  31.386839  35546.28830     1       1         0      0     3
2  43.200342  44169.18638     0       1         0      0     3
3  37.316995  81041.98639     1       0         0      1     2
4  40.954390  79353.01444     3       1         0      1     2

In [56]:
print(df_num.dtypes)

age          float64
income       float64
kids           int64
ownHome       object
subscribe     object
female        object
sum1           int32
dtype: object


In [64]:
ord(df_num.female)

TypeError: ord() expected string of length 1, but Series found

In [51]:
print(df_num.dtypes)

age          float64
income       float64
kids           int64
ownHome       object
subscribe     object
female        object
sum1           int32
dtype: object


In [25]:
del df_num['Id']

KeyError: 'Id'

In [26]:
del df_num['gender']



In [65]:
df_num.head()

age       income  kids ownHome subscribe female  sum1
0  47.316133  49482.81044     2       0         0      0     3
1  31.386839  35546.28830     1       1         0      0     3
2  43.200342  44169.18638     0       1         0      0     3
3  37.316995  81041.98639     1       0         0      1     2
4  40.954390  79353.01444     3       1         0      1     2

In [28]:
from sklearn.cluster import KMeans

In [29]:
model=KMeans(n_clusters=4,random_state=13)

In [30]:
model.fit(df_num)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=13, tol=0.0001, verbose=0)

In [34]:
model.predict(df_num)

array([3, 3, 3, 2, 2, 0, 1, 3, 3, 3, 3, 0, 0, 0, 3, 0, 3, 3, 0, 3, 3, 3,
       3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 0, 0, 3, 0, 3, 1, 0, 3, 3, 3, 0,
       3, 3, 0, 0, 3, 1, 0, 0, 0, 0, 3, 3, 3, 0, 1, 0, 3, 0, 3, 3, 0, 0,
       3, 0, 0, 0, 3, 0, 3, 3, 3, 2, 3, 0, 3, 3, 2, 3, 0, 3, 0, 3, 3, 3,
       0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0,
       1, 3, 0, 3, 1, 1, 3, 2, 0, 0, 3, 3, 2, 3, 0, 0, 2, 0, 3, 3, 3, 3,
       0, 3, 0, 3, 2, 3, 2, 2, 3, 0, 0, 0, 2, 2, 3, 0, 3, 3, 3, 2, 0, 0,
       2, 1, 3, 2, 0, 2, 2, 0, 2, 0, 0, 2, 3, 0, 2, 3, 0, 3, 0, 0, 3, 1,
       1, 0, 2, 3, 2, 2, 0, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3, 0,
       3, 0, 0, 3, 3, 0, 0, 3, 3, 0, 0, 0, 3, 3, 0, 3, 0, 0, 3, 1, 3, 3,
       3, 3, 0, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 3, 3, 3, 3,
       3, 3, 0, 3, 0, 3, 0, 3, 3, 3, 0, 3, 0, 3], d

In [35]:
df_num['sum1']=model.predict(df_num)

In [36]:
df_num.groupby('sum1').mean()

age        income      kids
sum1                                   
0     43.669314  63630.699002  1.443299
1     29.587043  21631.788196  1.063492
2     55.409681  89959.960352  0.360000
3     42.389094  47799.838146  1.434783

In [ ]:
#Cluster analysis after standardizing the data

In [66]:
from sklearn.preprocessing import StandardScaler

In [70]:
df_num1=df

In [77]:
df_num1.head()

age       income  kids ownHome subscribe female
0  47.316133  49482.81044     2       0         0      0
1  31.386839  35546.28830     1       1         0      0
2  43.200342  44169.18638     0       1         0      0
3  37.316995  81041.98639     1       0         0      1
4  40.954390  79353.01444     3       1         0      1

In [72]:
df_num1['female']=df_num1['gender'].apply(lambda x: '1' if x=='Female' else '0')
df_num1['ownHome']=df_num1['ownHome'].apply(lambda x: '1' if x=='ownYes' else '0')
df_num1['subscribe']=df_num1['subscribe'].apply(lambda x: '0' if x=='subNo' else '1')

In [75]:
del df_num1['Id']

In [76]:
del df_num1['gender']

In [78]:
scaler=StandardScaler()

In [79]:
scaler.fit(df_num1)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64, object were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [80]:
scaler.transform(df_num1)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64, object were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([[ 0.48213561, -0.07231042,  0.51916875, -0.94169658, -0.39223227,
        -1.04780824],
       [-0.77350095, -0.7655332 , -0.19202132,  1.06191317, -0.39223227,
        -1.04780824],
       [ 0.15770583, -0.33661777, -0.90321138,  1.06191317, -0.39223227,
        -1.04780824],
       ...,
       [-0.23409996, -0.16691287, -0.90321138, -0.94169658,  2.54950976,
        -1.04780824],
       [-0.63291349,  0.4880034 , -0.19202132, -0.94169658, -0.39223227,
        -1.04780824],
       [-0.53725748,  0.13621174,  2.65273895,  1.06191317, -0.39223227,
        -1.04780824]])

In [81]:
model.fit(df_num1)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=13, tol=0.0001, verbose=0)

In [82]:
model.predict(df_num1)

array([3, 3, 3, 2, 2, 0, 1, 3, 3, 3, 3, 0, 0, 0, 3, 0, 3, 3, 0, 3, 3, 3,
       3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 0, 0, 3, 0, 3, 1, 0, 3, 3, 3, 0,
       3, 3, 0, 0, 3, 1, 0, 0, 0, 0, 3, 3, 3, 0, 1, 0, 3, 0, 3, 3, 0, 0,
       3, 0, 0, 0, 3, 0, 3, 3, 3, 2, 3, 0, 3, 3, 2, 3, 0, 3, 0, 3, 3, 3,
       0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0,
       1, 3, 0, 3, 1, 1, 3, 2, 0, 0, 3, 3, 2, 3, 0, 0, 2, 0, 3, 3, 3, 3,
       0, 3, 0, 3, 2, 3, 2, 2, 3, 0, 0, 0, 2, 2, 3, 0, 3, 3, 3, 2, 0, 0,
       2, 1, 3, 2, 0, 2, 2, 0, 2, 0, 0, 2, 3, 0, 2, 3, 0, 3, 0, 0, 3, 1,
       1, 0, 2, 3, 2, 2, 0, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3, 0,
       3, 0, 0, 3, 3, 0, 0, 3, 3, 0, 0, 0, 3, 3, 0, 3, 0, 0, 3, 1, 3, 3,
       3, 3, 0, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 3, 3, 3, 3,
       3, 3, 0, 3, 0, 3, 0, 3, 3, 3, 0, 3, 0, 3], d

In [83]:
df_num1.columns

Index(['age', 'income', 'kids', 'ownHome', 'subscribe', 'female'], dtype='object')

In [84]:
df2=pd.DataFrame(df_num1)

In [86]:
df2.columns=df_num1.columns

In [87]:
df2.head()

age       income  kids ownHome subscribe female
0  47.316133  49482.81044     2       0         0      0
1  31.386839  35546.28830     1       1         0      0
2  43.200342  44169.18638     0       1         0      0
3  37.316995  81041.98639     1       0         0      1
4  40.954390  79353.01444     3       1         0      1

In [88]:
df2['sum2']=model.predict(df2)

In [89]:
df2.groupby('sum2').mean()

age        income      kids
sum2                                   
0     43.669314  63630.699002  1.443299
1     29.587043  21631.788196  1.063492
2     55.409681  89959.960352  0.360000
3     42.389094  47799.838146  1.434783